### ISSUE TITLE
systemd-networkd not started in generated live system

### ISSUE THREAD

**Issue by ulrichard** [fepitre/mmdebstrap#1]
I recently changed our live system from fakechroot to mmdebstrap. 
https://github.com/AminaBank/livedeb/pull/12
Now I discovered that after this change, the live system has no network connectivity. The system didn't get an IP address from DHCP. If I modify the commands to enable root on the generated image, I can execute "`systemctl start systemd-networkd`" to make networking work. 
I got the networking working in the live system working, by adding the following option to mmdebstrap: 
`-customize-hook='chroot "$1" systemctl enable systemd-networkd'`
What is the likelyhood that I also need to manually enable other services, that were automatically enabled with the fakechroot approach?

**Comment by fepitre** [comment]
This is not the official repository: https://gitlab.mister-muffin.de/josch/mmdebstrap
